import type { ExtractionResult } from "@/lib/types/extraction";

export function generateCssVariables(result: ExtractionResult): string {
  const lines: string[] = [
    `/* Generated by Pozzle — ${result.url} */`,
    `/* ${result.timestamp} */`,
    "",
    ":root {",
    "  /* Colors */",
  ];

  result.colors.forEach((color) => {
    lines.push(`  --color-${color.name}: ${color.hex};`);
  });

  lines.push("", "  /* Typography */");
  result.typography.forEach((type) => {
    lines.push(`  --font-size-${type.name}: ${type.fontSize};`);
    lines.push(`  --font-weight-${type.name}: ${type.fontWeight};`);
    lines.push(`  --line-height-${type.name}: ${type.lineHeight};`);
  });

  lines.push("", "  /* Spacing */");
  result.spacing.forEach((space) => {
    lines.push(`  --spacing-${space.name}: ${space.value};`);
  });

  lines.push("", "  /* Border Radius */");
  result.radius.forEach((radius) => {
    lines.push(`  --radius-${radius.name}: ${radius.value};`);
  });

  lines.push("}");
  return lines.join("\n");
}
