import type { ExtractionResult } from "@/lib/types/extraction";

export function generateTailwindTheme(result: ExtractionResult): string {
  const lines: string[] = [
    `/* Generated by Pozzle — ${result.url} */`,
    `/* ${result.timestamp} */`,
    "",
    "@theme inline {",
    "  /* Colors */",
  ];

  result.colors.forEach((color) => {
    lines.push(`  --color-${color.name}: ${color.hex};`);
  });

  // Dedupe font families
  const uniqueFamilies = new Map<string, string>();
  result.typography.forEach((type) => {
    if (type.fontFamily && !uniqueFamilies.has(type.fontFamily)) {
      const familyKey = type.fontFamily
        .replace(/['"]/g, "")
        .split(",")[0]
        .trim()
        .toLowerCase()
        .replace(/\s+/g, "-");
      uniqueFamilies.set(type.fontFamily, familyKey);
    }
  });

  if (uniqueFamilies.size > 0) {
    lines.push("", "  /* Font Families */");
    uniqueFamilies.forEach((key, family) => {
      lines.push(`  --font-${key}: ${family};`);
    });
  }

  lines.push("", "  /* Typography Scale */");
  result.typography.forEach((type) => {
    lines.push(`  --font-size-${type.name}: ${type.fontSize};`);
  });

  lines.push("", "  /* Spacing */");
  result.spacing.forEach((space) => {
    lines.push(`  --spacing-${space.name}: ${space.value};`);
  });

  lines.push("", "  /* Border Radius */");
  result.radius.forEach((radius) => {
    lines.push(`  --radius-${radius.name}: ${radius.value};`);
  });

  lines.push("}");
  return lines.join("\n");
}
